---
name: Packer

on: [push, pull_request]

jobs:
  packer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: packer validate
        uses: operatehappy/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: base.json

      - name: packer build
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: operatehappy/packer-github-actions@master
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
        with:
          command: build
          target: base.json
