---
name: Packer

on:
  push:
  pull_request:
  schedule:
    - cron: '9 1 * * *'

jobs:
  packer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: packer validate
        uses: 'docker://hashicorp/packer:light'
        with:
          args: validate -syntax-only base.json

      - name: packer build
        if: >-
          github.ref == 'refs/heads/main' &&
          (github.event_name == 'push' || github.event_name == 'schedule')
        uses: 'docker://hashicorp/packer:light'
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
        with:
          args: build base.json

      - name: Clean up snapshots
        if: github.ref == 'refs/heads/main' && github.event_name == 'schedule'
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
        run: |
          curl -sS \
            -H "Authorization: Bearer $HCLOUD_TOKEN" \
            'https://api.hetzner.cloud/v1/images?label_selector=mhnet-image=base' | \
          jq -r '.images|sort_by(.description)[:-3][].id' | \
          while read -r iid; do
            echo "Removing snapshot ${iid}"
            curl -sS \
            -X DELETE \
            -H "Authorization: Bearer $HCLOUD_TOKEN" \
            "https://api.hetzner.cloud/v1/images/${iid}"
          done
