---
name: Packer

on:
  push:

jobs:
  validate-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: packer validate
        uses: operatehappy/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: base.json

      - name: packer build
        uses: operatehappy/packer-github-actions@master
        with:
          command: build
          target: base.json
